### PR TITLE
Added project installer script

### PR DESCRIPTION
**Pull request by dorosch**
The script automatically installs a virtual environment, depending and the semantic space.

### CODE REVIEW

**Comment by stultus** [comment]
Thank you. I see some `sudo`s here and there. Do we need that ?

**Comment by dorosch** [comment]
Yes you need to sudo. I forgot to add)

**Comment by stultus** [comment]
I mean, when you use a virtualenv, you don't need sudo access right?  If we can remove the sudo, users with lesser privileges can use this.

**Comment by dorosch** [comment]
As it turned out, when picked virtualenv not need rights Sudo, you are right)

**Comment by nandajavarma** [comment]
Looks good to me. Thanks for this @dorosch .

Just checking, are you by any chance good with Docker?

**Pull request merged**
