### PR TITLE
general refactoring

### LINKED ISSUE #16: Refactoring
There are several common issues in sources that considered a bad practice:
- calling files/functions/variables camelCase
- using mixture of tabs and spaces (only spaces should be used)
- not properly writing comments (refer to pep8)

also several other pep8 violations.

### PR DESCRIPTION
**Pull request by sepulchered**
Done general refactoring (pep8 compliance mainly). Added required modules to `requirements.txt`.
Also added `pep8` module for checking pep8 compliance. Can be used as `pep8 --max-line-length=120 ./` in the root project folder.

Created new issue to rename files and other fixes #16 .

PS: would be great to create tests for code (basic integration and unit tests).

### CODE REVIEW

**Comment by nandajavarma** [comment]
@minimalparts @stultus I do not see any changes to the codebase as such. This PR basically fixes all the pep8 issues. Shall I go ahead and merge this? Have a look.

**Comment by minimalparts** [comment]
Just had a look and it all looks good to me. Thanks, @sepulchered! :)

Looking at the files, though, made me realise that most of the content in the utilities dir is now obsolete and can be thrown away. I'll open this as a separate issue.

**Comment by nandajavarma** [comment]
@asdofindia This is one of those tiny issues that got in after the refactoring. I have fixed this issue in the PR #26

**Comment by sepulchered** [comment]
Sorry for late answer. This package is used by setuptools (http://setuptools.readthedocs.io/en/latest/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources). Don't know how it got to the requirements. So thank you for fixing it @nandajavarma

**Pull request merged**
