### PR TITLE
Adding the Indexer to PeARS

### PR DESCRIPTION
**Pull request by nandajavarma**
This fixes the issue #25 

I am opening up this PR saw everyone approves of the indexer setup. It is not complete yet. Right now I have integrated the Browser history analyzer by @minimalparts to the PeARS repo. So as per the current code, whenever someone installs PeARS using the install.py script she/he will be prompted to index the firefox history.

I am now adding a daemon that listens to the HTTP calls, so it keeps indexing whenever a search happens.

### CODE REVIEW

**Comment by minimalparts** [comment]
Wow, this is a mighty PR :) I'll give it a go asap!!

**Comment by nandajavarma** [comment]
It looks mighty just because I made some structural changes in the app for the future. ;-) The extra functionality added(Browser history analyzer) is all you, @minimalparts. :-)

One can either index firefox history while installing, that is by running install.sh or separately by running browser_history_indexer.py.

**Comment by minimalparts** [comment]
Hey @nandajavarma! Looks fantastic :) If you have a minute, could you expand a bit on the new structure? Nice to have the pears directory with both indexer and searcher. But do we still need app/?

Mini comments, as I notice things:
- should we have something that automatically adds the local pear (created by the indexer) to shared_pears_ids.txt? Just on the grounds that it will anyway be faster to search than when accessing it from the network? What do you think?
- can we now get rid of retrieve_pages.py? There is also create_history_db.py hanging about, but that actually has some code from @veesa to take the .pearsignore file into account, which I haven't yet integrated. So we should keep it until we've merged things together.
- can we rename db_updrade.py to db_upgrade.py? :)

**Comment by nandajavarma** [comment]
Hey @minimalparts ,

My PR removes the app/ directory from the root of the app(Or did I forget to commit it... Nope. Just checked. Gone!).
To address your mini comments:
- Once I get this Daemon working, I will write code to add our databases. Then, the indexer will be populating the databases with all the data it creates. So I thought I will add that code once the databases are in place.
- Okay. We will keep it like that for now and clean up after merge.
- db_updrade.py --> db_upgrade.py: Consider it done! :-P

**Comment by nandajavarma** [comment]
I will elaborate on the structure in the PR message.

**Comment by minimalparts** [comment]
<@minimalparts bangs her head against the wall>
Oh yeah, that was my local copy of app/ hanging in there...

Rest: ok, super-cool. :) Shall we merge this already? Or do you want to add the daemon first? (Btw, in case you want to reuse code, there was a start of daemon there: https://github.com/PeARSearch/browsing-history-analyser/blob/master/http_proxy.py).

**Comment by stultus** [comment]
we can merge this right? @nandajavarma ?

**Comment by nandajavarma** [comment]
@stultus I will make the rest of the changes in a separate PR. You can merge it now.

**Pull request merged**
